### ISSUE TITLE
Need request caching

### ISSUE THREAD

**Issue by MadhavJivrajani** [MadhavJivrajani/go-corona-go#1]
Every time a command is executed, a new request is made to the API, request caching may be helpful here using something like [go-cache](https://github.com/patrickmn/go-cache).

When a command is executed, the cache is first checked, if contents are found then those contents are used else a new request is sent to the API.

**Comment by GaruGaru** [comment]
Can I work on this ?

**Comment by MadhavJivrajani** [comment]
Sure!
